### ISSUE TITLE
Singularity: access issues to external data

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/MIP#1577]
**Describe the bug**
Startin the MIP pipeline on external data fails. We believe that the issue is due to paths to external data are not bound to Singularity. The pipeline is broken in BWA indexing due to bwa-mem and fastqc not being able to open the files. 

**To Reproduce**
1. Submit recipe 'cg workflow mip-dna -c fancyfawn'
2. Go to '/home/proj/production/rare-disease/cases/fancyfawn/analysis/ACC2772A1/bwa_mem/info/'
3. Open log 'bwa_mem_ACC2772A1.0.stderr.txt'
4. See error 'bwa_mem/fastqc: fail to open file `/home/proj/production/rare-disease/cases/fancyfawn/wes/ACC2772A1/fastq/6_171015_C7RL9ACXX_ACC2772A1_XXXXXX_1.fastq.gz'

**Expected behavior**
bwa-mem to align the reads

**Software version (please complete the following information):**
 - MIP: [v8.2.6]
 - CG: [9.25.5]

**Comment by talnor** [comment]
Alternatively we include all external data in housekeeper if this is prefereable

**Comment by henrikstranneheim** [comment]
I agree - this is a likely cause. The best long term solution is like Tanja said - include the external data in HK as all bundles are already bound.

However:
You can extend the paths to bind per recipe using the `singularity_recipe_bind_path` parameter. It looks like this in the current MIP prod config:
```
singularity_recipe_bind_path:
  fastqc_ar:
   - /home/proj/production/rare-disease/
   - /home/proj/production/housekeeper-bundles
   - /home/proj/production/demultiplexed-runs
  bwa_mem:
   - /home/proj/production/rare-disease/
   - /home/proj/production/housekeeper-bundles
   - /home/proj/production/demultiplexed-runs
```

Closing this as it is not really a MIP issue, but more of a Hasta data management issue.
