### ISSUE TITLE
human_genome_build and rank_model_version params now missing in yaml .conf file

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/MIP#539]
Since a few months these two parameters are missing from the .yaml conf files of the analyses. This had the effect that when the case was parsed they were not saved into scout database, and as a consequence they're not displayed at the case level. 
Here's an example: https://scout-stage.scilifelab.se/cust000/F0010948-validation.

How do we fix it? @moonso @henrikstranneheim @patrikgrenfeldt @jemten

**Comment by jemten** [comment]
Is it missing in the .yaml file that MIP generates?

**Comment by northwestwitch** [comment]
I think so. It looks like something happened in all cases runned from Oct 2017.

**Comment by northwestwitch** [comment]
At least those I checked

**Comment by northwestwitch** [comment]
We were reasoning that this could be also due to cg, so I'm adding also @ingkebil to this conversation! :)

**Comment by ingkebil** [comment]
Team Teamname (TTN) added this user story to its current sprint. @patrickgrenfeldt is taking it up.

**Comment by henrikstranneheim** [comment]
It should be present in the MIP file [FAMILY_ID]_qc_sample_info.yaml e.g.:
```
human_genome_build:
  path: [PATH]/references_6.0/GRCh37_homo_sapiens_-d5-.fasta
  source: GRCh
  version: 37
.
.
    rank_model:
      file: rank_model_cmms_-v1.20-.ini
      path: [PATH]/references_6.0/rank_model_cmms_-v1.20-.ini
      version: 1.20
.
.
    sv_rank_model:
      file: svrank_model_cmms_-v1.2-.ini
      path: [PATH]/references_6.0/svrank_model_cmms_-v1.2-.ini
      version: 1.2
```
