### ISSUE TITLE
Add input SV vcf for vcf_rerun to qc_sample_info

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#548]

**Comment by henrikstranneheim** [comment]
Added as: 
```
sv_combinevariantcallsets:
    path: FID_SV.0.stderr.txt
    sv_bcf_file:
      path: FID.bcf
```
